{% set name = "amazon-braket-schemas" %}
{% set version = "1.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-braket-schemas-{{ version }}.tar.gz
  sha256: 08e07a83ff958dbdcd6018bcab3e24a35ec48e303252773aabca2f573785a063

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pydantic >=1.8.2,<2.0.0
    - python >=3.7

test:
  imports:
    - braket
    - braket._schemas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-schemas-python
  summary: An open source library that contains the schemas for Amazon Braket
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
