{% set name = "amazon-braket-schemas" %}
{% set version = "1.32.0" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: be9f7ee403677a2abe7658d5a102227f93fae4682ebba7fe520ab663da7fcf0e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - setuptools ==81.0.0
    - pydantic >2
    - python >={{ python_min }}

test:
  imports:
    - braket
    - braket._schemas
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/amazon-braket-schemas-python
  summary: An open source library that contains the schemas for Amazon Braket
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
