{% set name = "amazon-braket-schemas" %}
{% set version = "1.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-braket-schemas-{{ version }}.tar.gz
  sha256: 95ac9917d35a0816cd10d9f58aec51694e4601aea2e2f15d9f5851725aa43688

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pydantic >=1.8.2,<2.0.0
    - python >=3.7

test:
  imports:
    - braket
    - braket._schemas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-schemas-python
  summary: An open source library that contains the schemas for Amazon Braket
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
