{% set name = "amazon-braket-schemas" %}
{% set version = "1.23.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2fa59bdcfa87f05294374a9ebd80530acbf78d58268a52680d2937892d7b91c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pydantic >2
    - python >={{ python_min }}

test:
  imports:
    - braket
    - braket._schemas
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/amazon-braket-schemas-python
  summary: An open source library that contains the schemas for Amazon Braket
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
