{% set name = "amazon-braket-schemas" %}
{% set version = "1.22.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2fe23bd46d62c38ce90acac76c0e269699aadee97b81ce90aa08815d18a398e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - pydantic >2
    - python >=3.9

test:
  imports:
    - braket
    - braket._schemas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-schemas-python
  summary: An open source library that contains the schemas for Amazon Braket
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
